--- COMANDOS PARA CRIAÇÃO DAS TABELAS E SEUS RELACIONAMENTOS ---

--- COMANDOS PARA POPULAÇÃO DAS TABELAS ---



--- COMANDOS PARA A CONSULTA 1 ---

--- COMANDOS PARA A CONSULTA 2 ---

--- COMANDOS PARA A CONSULTA 3 ---

--- COMANDOS PARA A CONSULTA 4 ---

--- COMANDOS PARA A CONSULTA 5 ---

--- COMANDOS PARA A CONSULTA 6 ---

--- COMANDOS PARA A CONSULTA 7 ---

--- COMANDOS PARA A CONSULTA 8 ---

--- COMANDOS PARA A CONSULTA 9 ---

--- COMANDOS PARA CRIAÇÃO E EXEMPLO DE USO DA "VIEW" ---

--- COMANDOS PARA CRIAÇÃO E EXEMPLO DE USO DA FUNÇÃO ---

--- COMANDOS PARA CRIAÇÃO E EXEMPLO DE USO DA "STORED PROCEDURE" ---

--- COMANDOS PARA CRIAÇÃO E EXEMPLO DE USO DA "TRIGGER" ---
